name: Remove Origin Arrays

on:
  # Run every 5 days
  schedule:
    - cron: '0 0 */5 * *'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  remove-origin-arrays:
    runs-on: ubuntu-latest
    outputs:
      changes_pushed: ${{ steps.commit_changes.outputs.changes_pushed }}

    steps:
      - name: Check for running workflows
        id: check_workflows
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            // Get all running workflows
            const runningWorkflows = await github.rest.actions.listWorkflowRunsForRepo({
              owner,
              repo,
              status: 'in_progress'
            });

            // Filter out the current workflow
            const otherRunningWorkflows = runningWorkflows.data.workflow_runs.filter(
              run => run.id !== context.runId
            );

            if (otherRunningWorkflows.length > 0) {
              console.log('Other workflows are currently running. Cancelling this workflow.');
              core.setFailed('Other workflows are currently running. Please try again later.');
              return false;
            }

            console.log('No other workflows are running. Proceeding with execution.');
            return true;

      - name: Checkout repository
        if: steps.check_workflows.outputs.result == 'true'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for proper git operations
          token: ${{ secrets.PAT }}  # 使用个人访问令牌进行身份验证

      - name: Set up Python
        if: steps.check_workflows.outputs.result == 'true'
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        if: steps.check_workflows.outputs.result == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Remove Origin Arrays script
        if: steps.check_workflows.outputs.result == 'true'
        id: run_script
        run: |
          python remove_origin_arrays.py --base-dir pic/data --bark-url ${{ secrets.BARK_URL || 'https://api.day.app/FXxtHPEhbvdzxrgRpBW7E' }}

      - name: Configure Git
        if: steps.check_workflows.outputs.result == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Commit and push changes
        if: steps.check_workflows.outputs.result == 'true'
        id: commit_changes
        run: |
          # Check if there are any changes
          if [[ -n $(git status --porcelain) ]]; then
            git add -A
            git commit -m "移除索引文件中的origin和originURL数组: $(date +'%Y-%m-%d')"
            # 使用个人访问令牌进行推送，确保有足够的权限
            git push https://${{ secrets.PAT }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
            echo "changes_pushed=true" >> $GITHUB_OUTPUT
          else
            echo "没有需要提交的更改"
            echo "changes_pushed=false" >> $GITHUB_OUTPUT
          fi

  # Trigger mirror sync after removing origin arrays
  trigger-mirror-sync:
    needs: remove-origin-arrays
    runs-on: ubuntu-latest
    if: ${{ needs.remove-origin-arrays.outputs.changes_pushed == 'true' }}  # Only run if changes were pushed

    steps:
      - name: Trigger mirror sync workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'sync_mirror_repositories.yml',
              ref: 'main'  # or your default branch
            })
